from typing import Protocol
from uuid import UUID

from ...read_models import SubmittedTransactionSpec, TransactionItem


class TransactionCommandRepository(Protocol):
    async def add(self, transaction: TransactionItem) -> None: ...

    async def insert_submitted(self, spec: SubmittedTransactionSpec) -> None: ...

    async def mark_pending_if_submitted(self, request_id: UUID) -> int: ...

    async def fail_if_submitted(self, request_id: UUID, safe_error: str) -> int: ...

    async def fail_if_pending(self, request_id: UUID, safe_error: str) -> int: ...

    async def claim_for_execution(self, request_id: UUID) -> TransactionItem | None: ...

    async def complete_if_in_progress(self, request_id: UUID, safe_error: str | None) -> int: ...

    async def lock_by_request_id(self, request_id: UUID) -> TransactionItem | None: ...
