"""add wallet tables version 1

Revision ID: d377d8c90992
Revises: 23fa0ceb69ca
Create Date: 2026-07-29 22:34:21.335585

"""
import uuid
from datetime import UTC, datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd377d8c90992'
down_revision: Union[str, Sequence[str], None] = '23fa0ceb69ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CURRENCY_USD_ID = uuid.UUID("00000000-0000-4000-8000-000000000101")
CURRENCY_USDT_ID = uuid.UUID("00000000-0000-4000-8000-000000000102")
SEED_UPDATED_AT = datetime(2026, 1, 1, tzinfo=UTC)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=6), nullable=False),
    sa.Column('precision', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("type IN ('fiat', 'crypto')", name='ck_currencies_type_valid'),
    sa.CheckConstraint('precision >= 0 AND precision <= 18', name='ck_currencies_precision_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('admin_wallets',
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_admin_wallets_amount_nonnegative'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('currency_id')
    )
    op.create_table('user_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_user_wallets_amount_nonnegative'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'currency_id', name='uq_user_wallets_user_id_currency_id')
    )
    op.create_index('ix_user_wallets_user_id', 'user_wallets', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('source_wallet_id', sa.UUID(), nullable=True),
    sa.Column('source_amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('dest_wallet_id', sa.UUID(), nullable=True),
    sa.Column('dest_amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(type = 'deposit' AND source_wallet_id IS NULL AND dest_wallet_id IS NOT NULL) OR (type = 'withdrawal' AND source_wallet_id IS NOT NULL AND dest_wallet_id IS NULL) OR (type IN ('exchange', 'transfer') AND source_wallet_id IS NOT NULL AND dest_wallet_id IS NOT NULL AND source_wallet_id <> dest_wallet_id)", name='ck_transactions_type_wallet_shape'),
    sa.CheckConstraint("status IN ('completed', 'failed')", name='ck_transactions_status_v1'),
    sa.CheckConstraint("type IN ('deposit', 'exchange', 'withdrawal', 'transfer')", name='ck_transactions_type_valid'),
    sa.CheckConstraint('source_amount > 0 AND dest_amount > 0', name='ck_transactions_amounts_positive'),
    sa.ForeignKeyConstraint(['dest_wallet_id'], ['user_wallets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_wallet_id'], ['user_wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_created_at_id', 'transactions', [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###

    op.execute(
        sa.text(
            """
            INSERT INTO currencies (id, type, name, label, precision)
            VALUES
                (:usd_id, 'fiat', 'US Dollar', 'USD', 4),
                (:usdt_id, 'crypto', 'Tether USD', 'USDT', 8)
            ON CONFLICT (id) DO NOTHING
            """
        ).bindparams(
            sa.bindparam("usd_id", CURRENCY_USD_ID, type_=sa.UUID()),
            sa.bindparam("usdt_id", CURRENCY_USDT_ID, type_=sa.UUID()),
        )
    )
    op.execute(
        sa.text(
            """
            INSERT INTO admin_wallets (currency_id, amount, updated_at)
            VALUES
                (:usd_id, 0, :updated_at),
                (:usdt_id, 0, :updated_at)
            ON CONFLICT (currency_id) DO NOTHING
            """
        ).bindparams(
            sa.bindparam("usd_id", CURRENCY_USD_ID, type_=sa.UUID()),
            sa.bindparam("usdt_id", CURRENCY_USDT_ID, type_=sa.UUID()),
            sa.bindparam("updated_at", SEED_UPDATED_AT, type_=sa.DateTime(timezone=True)),
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_created_at_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_user_wallets_user_id', table_name='user_wallets')
    op.drop_table('user_wallets')
    op.drop_table('admin_wallets')
    op.drop_table('currencies')
    # ### end Alembic commands ###
